version: "3.3"

services:
  grafana:
    environment:
      - GF_SERVER_DOMAIN=crypto-indicators.org
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_DISABLE_LOGIN_FORM=true
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    restart: always
    volumes:
      - "./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    depends_on:
      - grafana

  # Ethereum full node
  ethereum:
    image: ethereum/client-go:latest
    command: --http --ws --http.addr 0.0.0.0 --ws.addr 0.0.0.0
    ports:
      - 8545:8545
      - 8546:8546
    volumes:
      - "ethereum_data:/root/.ethereum"
    restart: always

  ethereum_crawlers:
    environment:
      - FULL_NODE_URL=ws://localhost:8546
    depends_on:
      - ethereum

volumes:
  ethereum_data:
    driver: local
