version: "3.3"

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: always

  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=crypto_indicators
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=passw0rd
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_HTTP_FLUX_ENABLED=true
      - INFLUXDB_LOGGING_LEVEL=warn
      - INFLUXDB_HTTP_LOG_ENABLED=false
    volumes:
      - "influxdb_data:/var/lib/influxdb"
    restart: always

  logstash:
    build:
      context: ./containers/logstash
    image: logstash:latest
    depends_on:
      - redis
      - influxdb
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=passw0rd
    volumes:
      - "grafana_data:/var/lib/grafana"
      - "./configs/grafana/provisioning:/etc/grafana/provisioning:ro"
    depends_on:
      - influxdb
    restart: always

  crypto_crawlers:
    build:
      context: ./nodejs
      dockerfile: Dockerfile.crawlers
    image: crypto-crawlers:latest
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    restart: always

  ethereum_crawlers:
    build:
      context: ./nodejs
      dockerfile: Dockerfile.ethereum
    image: ethereum-crawlers:latest
    environment:
      - REDIS_URL=redis://redis:6379
      - FULL_NODE_URL=wss://mainnet.infura.io/ws/v3/6866aa0c8c3d48638fedf2d83c85f4b8
    depends_on:
      - redis
    restart: always

volumes:
  influxdb_data:
    driver: local
  grafana_data:
    driver: local
