apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: crypto_indicators
    user: admin
    password: passw0rd
    isDefault: true
    editable: false
    jsonData:
      httpMode: POST
