{
 "title": "Ethereum",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Miner Revenue in ETH",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "eth_miner_revenue",
     "query": "SELECT sum(\"revenue\") FROM \"eth_miner_revenue\" WHERE $timeFilter GROUP BY time(5m) fill(0)",
     "select": [
      [
       { "params": [ "revenue" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Miner Revenue in USD",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "eth_miner_revenue",
     "select": [
      [
       { "params": [ "revenueUSD" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gas Price",
   "type": "graph",
   "description": "Gas Price from gasnow.org",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "eth_gas_price",
     "query": "SELECT mean(\"rapid\"), mean(\"fast\"), mean(\"standard\"), mean(\"slow\") FROM \"eth_gas_price\" WHERE $timeFilter GROUP BY time(1m) fill(linear)",
     "select": [
      [
       { "params": [ "rapid" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rapid" ], "type": "alias" }
      ],
      [
       { "params": [ "fast" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "fast" ], "type": "alias" }
      ],
      [
       { "params": [ "standard" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "standard" ], "type": "alias" }
      ],
      [
       { "params": [ "slow" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "slow" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}