{
 "title": "Global",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Buy - Sell Volume",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "kline_ext",
     "query": "SELECT sum(\"volume_quote_buy\") - sum(\"volume_quote_sell\") FROM \"kline_ext\" WHERE (\"bar_size\" = '60000') AND $timeFilter GROUP BY time(5m) fill(0)",
     "select": [
      [
       { "params": [ "volume_quote_buy" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ],
      [
       { "params": [ "volume_quote_sell" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "bar_size", "operator": "=", "value": "60000" }
     ]
    }
   ]
  },
  {
   "title": "VPIN per Pair",
   "type": "graph",
   "description": "(buy-sell)/total",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (sum(\"volume_quote_buy\")-sum(\"volume_quote_sell\"))/sum(\"volume_quote\") FROM \"kline_ext\" WHERE (\"bar_size\" = '60000') AND $timeFilter GROUP BY time(5m), \"pair\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VPIN",
   "type": "graph",
   "description": "(buy-sell)/total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "kline_ext",
     "query": "SELECT (sum(\"volume_quote_buy\")-sum(\"volume_quote_sell\"))/sum(\"volume_quote\") FROM \"kline_ext\" WHERE (\"bar_size\" = '60000') AND $timeFilter GROUP BY time(5m) fill(0)",
     "select": [
      [
       { "params": [ "volume_buy" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "bar_size", "operator": "=", "value": "60000" }
     ]
    }
   ]
  },
  {
   "title": "Volume/BTC_Volume",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"quoteVolume\")/mean(\"btcQuoteVolume\") FROM \"btc_volume_ratio\" WHERE (\"base\" != 'BTC') AND $timeFilter GROUP BY time(3m), \"base\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}