{
 "title": "OKEx",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "VPIN",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT abs(sum(\"volume_quote_buy\")-sum(\"volume_quote_sell\"))/sum(\"volume_quote\") FROM \"kline_ext\" WHERE (\"exchange\" = 'OKEx' AND \"market_type\" = 'Swap') AND $timeFilter GROUP BY time(5m), \"pair\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Estimated Funding Rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "pair" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "okex_funding_rate",
     "select": [
      [
       { "params": [ "estimatedRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "OKEx" }
     ]
    }
   ]
  },
  {
   "title": "Funding Rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "pair" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "okex_funding_rate",
     "select": [
      [
       { "params": [ "fundingRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "OKEx" }
     ]
    }
   ]
  },
  {
   "title": "Price Change Percent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"close\")  / mean(\"open\") -1 FROM \"ticker\" WHERE (\"exchange\" = 'OKEx' AND \"marketType\" = 'Swap') AND $timeFilter GROUP BY time(5m), \"pair\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}